on:
  release:
    types: [published]

jobs:
  publish:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pdm sync -d
      - name: Build
        run: |
          pdm build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
