on:
  release:
    types: [published]

jobs:
  publish:
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pdm sync -d

      - name: Build
        uses: pdm-project/setup-pdm@main
        run: |
          pdm build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
